global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using SampleDotnet.RepositoryFactory.Interfaces;
global using SampleDotnet.RepositoryFactory.Tests.Models;
global using Shouldly;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Xunit;