global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.Extensions.DependencyInjection;
global using SampleDotnet.RepositoryFactory;
global using SampleDotnet.RepositoryFactory.Interfaces;
global using System.Data;
global using System.Linq.Expressions;
global using System.Transactions;